defaults:
  - base_dhmamba_mse
  - _self_
data:
  batch_size: 16
  num_workers: 4
  num_points: 4096
  data_dir: "./data/ForestSemantic_Simple/tiles_filtered_fps"
  augmentations_list: ['rotate', 'scale', 'shift']
  fold_idx: 0
  dataset_type: ForestSemantic_Simple
  split_json_path: "./data/ForestSemantic_Simple/splits.json"
  use_normalization: true
  calculate_avg_dist: true


model:
  num_classes: 2
  avg_volume_dist: 0.015171
  avg_chamfer_dist: 0.002446
  dist: "volume"  # "volume" or "chamfer" or "interpolate"
  num_group: 128
  group_size: 32
  trans_dim: 384
  alpha: 10.0  # chamfer距离阈值倍数
  HGNeighbors: 8
  # resume: "/home/wjzhang/workspace/codes/foliage_segmentation/Results/ForestSemantic_Simple/dhmamba_mse/fold_0/exp_20250919_111723/checkpoints/0-74-val_mIoU0.64.ckpt"


optimizer:
  learning_rate: 0.0002
  weight_decay: 0.00005
  max_epochs: 100
  eta_min: 0.000001
  warmup_epochs: 5

trainer:
  max_epochs: 100
  accelerator: "gpu"
  devices: [0]

comet:
  # name: "ForestSemantic_Simple_dhmamba_mse_chamfer_lr2e-4_bs16"
  name: "ForestSemantic_Simple_dhmamba_mse_volume_lr2e-4_bs16"
  # name: "ForestSemantic_Simple_dhmamba_ms_interpolate_lr2e-4_bs16"
