defaults:
  - base_dhmamba
  - _self_
data:
  batch_size: 16
  num_workers: 4
  num_points: 4096
  data_dir: "./data/Larch/tiles_filtered_fps"
  augmentations_list: ['rotate', 'scale', 'shift']
  fold_idx: 0
  dataset_type: Larch
  split_json_path: "./data/Larch/splits.json"
  use_normalization: true


model:
  num_classes: 2
  HGNeighbors: 8
  resume: "/home/wjzhang/workspace/codes/foliage_segmentation/Results/Larch/dhmamba/fold_0/exp_20250920_113825/0-81-val_mIoU0.55.ckpt"
optimizer:
  learning_rate: 0.0002
  weight_decay: 0.00005
  max_epochs: 100
  eta_min: 0.000001
  warmup_epochs: 5

trainer:
  max_epochs: 100
  accelerator: "gpu"
  devices: [1]

comet:
  name: "Larch_dhmamba_lr2e-4_bs16"
